# Generated by Django 4.1.1 on 2022-11-24 12:02

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('monay', '0003_alter_cliente_fotocliente_delete_fotoscliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='emailConf',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fotoCliente',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='loja/imagens'),
        ),
    ]
