# Generated by Django 4.1.1 on 2022-11-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monay', '0004_cliente_email_cliente_emailconf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='emailConf',
        ),
    ]
