# Generated by Django 4.1.1 on 2022-11-29 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monay', '0006_remove_cliente_fotocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='contaCliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monay.conta'),
            preserve_default=False,
        ),
    ]
