# Generated by Django 4.1.1 on 2022-11-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monay', '0008_remove_extrato_tipoextrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrato',
            name='todasOperacoes',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
